apiVersion: v1
data:
  container-helper.yaml: |+
    ---
    response: "Marge"
    tcpchecks:
      - name: homer.simpson
        host: homer-service.simpson
        port: 8080
      - name: selma.bouvier
        host: selma-service.bouvier
        port: 8080
      - name: patty.bouvier
        host: patty-service.bouvier
        port: 8080

kind: ConfigMap
metadata:
  labels:
    app: marge
  name: marge-container-helper
  namespace: simpson
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: marge
  name: marge-service
  namespace: simpson
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: marge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: marge
  name: marge-deployment
  namespace: simpson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marge
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: marge
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/ralvares/container-helper:minimal
        imagePullPolicy: Always
        name: container-helper
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /container-helper/
          name: container-helper-yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: marge-container-helper
        name: container-helper-yaml
